### ISSUE TITLE
wagrapple-0.9.6 crash w/ mc 1.15.2

### ISSUE THREAD

**Issue by umjammer** [Azim-D3Tm/WAGrappleMod#1]
what's wrong?
w/o wagrapple-0.9.6.jar in mod dir, it works fine.

crash log is here

https://gist.github.com/umjammer/aa1c85bb15ceecd37bd3f402fca2b1dd

and latest.log

https://gist.github.com/umjammer/0aca423ecfe0f81c6b0f759c82780992

**Comment by Azim** [comment]
Try without optifine and see if the issue is still there

**Comment by umjammer** [comment]
oh it works! w/o optifine.
i'm looking forward to work this w/ optifine, thanks

**Comment by Azim** [comment]
That isnt something of high priority in my opinion - in fact, i think, that optifine isnt something worth using in a modpack at all - it conflicts with a lot of stuff, it is closed source, and it is against Minecraft's EULA to buy capes. But that is, of course, one's personal choice on what to use and what to not use.

I will look into what may be the issue, but dont expect the fix until after the full release.
